<a href="https://colab.research.google.com/github/Pritipirojia/AI_Engineering_Tutorial_Notes/blob/main/numpy_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
numpy_array=np.array([1,2,3,4,5])

In [ ]:
numpy_array

array([1, 2, 3, 4, 5])

In [ ]:
type(numpy_array)

numpy.ndarray

In [ ]:
TwoDArray=np.array([[1,2,3],[4,5,6]])

In [ ]:
TwoDArray

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(TwoDArray)

numpy.ndarray

np.array()--- > Creating the MultiDimensional Arrays.

dtype paameter ---> which can help us out with deciding about the size of the data we are going to store inside our array.

In [ ]:
np.array([1,2,3,4,5],dtype=np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [ ]:
np.array([1,2,3,4,5],dtype=np.int64)

array([1, 2, 3, 4, 5])

In [ ]:
empty_list=[]
for i in range(16):
  empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [ ]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

arange() ---> It helps us out with providing the values over a certain range.

In [ ]:
np.arange(5,21)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arange_data=np.arange(1,17)

In [ ]:
arange_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

np.reshape()--- > It helps us out with changing the shape of the arrayas per our needs

In [ ]:
arange_data.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [ ]:
np.arange(2,17,2).reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

ones()---> initialise the weight of the neurons in the neural network architecture

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
### zeros()

np.zeros((4,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## random()---> It helps us out with generating any random values from 0 to 1 inside our matrix

In [ ]:
np.random.random((3,4))

array([[0.94634098, 0.51900075, 0.28462384, 0.06624428],
       [0.71415554, 0.22806206, 0.58486347, 0.34570313],
       [0.63064048, 0.4544327 , 0.14711908, 0.73461425]])

### Identity() ---> It helps us out with creating the matrix as an Identity Matrix (square matrix ---> Rows=Column)

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## linspace() ---> It makes sure that every value with the given range is going to have similar distance with each other.

In [ ]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

Attributes

#ndim ---> ndim stands for n dimension

In [ ]:
arr=np.array([1,2,3])

In [ ]:
arr.ndim

1

In [ ]:
array=np.array([[[1,2],[4,5]],[[3,7],[8,9]]])

In [ ]:
array.ndim

3

In [ ]:
np.array([[1,2],[3,4]]).ndim

2

## shape ----> It provides us with the idea about the rows, columns in our dataset or in array

In [ ]:
arrayy=np.array([[1,3,5],[4,6,7],[2,8,9]])

In [ ]:
arrayy

array([[1, 3, 5],
       [4, 6, 7],
       [2, 8, 9]])

In [ ]:
arrayy.shape

(3, 3)

In [ ]:
ThreeDArray=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])

In [ ]:
ThreeDArray.shape

(2, 2, 2)

## size ---> Total number of Elements present inside our Dataset or Array.

In [ ]:
array_elements=np.arange(5,57)

In [ ]:
array_elements.size

52

In [ ]:
np.array([[1,2],[3,4],[5,6]]).itemsize

8

In [ ]:
np.array([[1,2],[3,4],[5,6]],dtype=np.int32).itemsize

4

## itemsize ---> provides with the idea about the size of a unique element inside our array in bytes

## dtype ---> It provides us with the idea about the type of every item inside our array

In [ ]:
np.array([[1,2,3],[4,5,6]]).dtype

dtype('int64')

## astype()---> It will help us out with figuring out the data type of the column in the dataset in pandas and it will be used in the numpy as well for getting the data type change of our overall array

In [ ]:
array=np.arange(1,10).reshape(3,3)

In [ ]:
array.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
type(array)

numpy.ndarray

In [ ]:
array.dtype

dtype('int64')

In [ ]:
array=array.astype('float64')

In [ ]:
array.dtype

dtype('float64')

## Mathematical operations in numpy

## Scalar Operations ---> A scalar value operation will be done with the array or a numeric value (e.g. 1,4)

In [ ]:
array=np.random.random((3,3))*100

In [ ]:
array=np.round(array)

In [ ]:
array

array([[83., 36., 71.],
       [95., 78., 74.],
       [51., 12., 64.]])

In [ ]:
array=array.astype('int32')

In [ ]:
array

array([[83, 36, 71],
       [95, 78, 74],
       [51, 12, 64]], dtype=int32)

## scalar operations with our matrix or array

In [ ]:
array+2

array([[85, 38, 73],
       [97, 80, 76],
       [53, 14, 66]], dtype=int32)

In [ ]:
array-5

array([[78, 31, 66],
       [90, 73, 69],
       [46,  7, 59]], dtype=int32)

## we can apply scalar operations with the array in terms of arithmetic operations

In [ ]:
a=5
b=6
a>b

False

In [ ]:
array

array([[83, 36, 71],
       [95, 78, 74],
       [51, 12, 64]], dtype=int32)

In [ ]:
array>60

array([[ True, False,  True],
       [ True,  True,  True],
       [False, False,  True]])

## vector operations ---> Operations will be in between the given number of matrices

In [ ]:
arr1=np.arange(1,17).reshape(4,4)

In [ ]:
arr2=np.arange(17,33).reshape(4,4)

In [ ]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [ ]:
arr1+arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [ ]:
arr2-arr1

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [ ]:
arr1*arr2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

## Important functions in numpy for machine learning and data science

## max() ----> It is going to be used to calculate the max value inside a matrix or an array.

## syntax for max() --> np.max(array)

In [ ]:
max_value=np.max(arr1)

In [ ]:
max_value

np.int64(16)

In [ ]:
array_data=np.round(np.random.random((4,4))*100).astype('int32')

In [ ]:
array_data

array([[56, 43, 11, 20],
       [22, 24, 39, 70],
       [51, 55, 94, 85],
       [83, 49, 99, 33]], dtype=int32)

In [ ]:
max_value=np.max(array_data)

In [ ]:
max_value

np.int32(99)

## axis ---> It provides us with the idea about any operation value inside a specific row or column or we can get a specific value row wise or column wise

### axis=0 ---> column wise operation

### axis-1 ---> row wise operation

In [ ]:
array_data

array([[56, 43, 11, 20],
       [22, 24, 39, 70],
       [51, 55, 94, 85],
       [83, 49, 99, 33]], dtype=int32)

In [ ]:
np.max(array_data,axis=0)

array([83, 55, 99, 85], dtype=int32)

In [ ]:
np.max(array_data,axis=1)

array([56, 70, 94, 99], dtype=int32)

## min()---> It will be used for calculating the minimum value from the matrix or array
## syntax --> np.min()

In [ ]:
array_data

array([[56, 43, 11, 20],
       [22, 24, 39, 70],
       [51, 55, 94, 85],
       [83, 49, 99, 33]], dtype=int32)

In [ ]:
np.min(array_data)

np.int32(11)

In [ ]:
np.min(array_data, axis=1)

array([11, 22, 51, 33], dtype=int32)

In [ ]:
np.min(array_data, axis=0)

array([22, 24, 11, 20], dtype=int32)

In [ ]:
array=np.arange(1,10)

In [ ]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.min(array)

np.int64(1)

In [ ]:
np.max(array)

np.int64(9)

## sum()---> calculates the sum of all of the values of a given matrix
# symntax for sum()---> np.sum()

In [ ]:
array_data

array([[56, 43, 11, 20],
       [22, 24, 39, 70],
       [51, 55, 94, 85],
       [83, 49, 99, 33]], dtype=int32)

In [ ]:
np.sum(array_data)

np.int64(834)

In [ ]:
np.sum(array_data, axis=1)

array([130, 155, 285, 264])

In [ ]:
np.sum(array_data, axis=0)

array([212, 171, 243, 208])

## prod()---> It helps with calculating the product of all values inside the matrix
# syntax ---> np.prod()

In [ ]:
array_data

array([[56, 43, 11, 20],
       [22, 24, 39, 70],
       [51, 55, 94, 85],
       [83, 49, 99, 33]], dtype=int32)

In [ ]:
np.prod(array_data)

np.int64(8442555979710416896)

In [ ]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.prod(array)

np.int64(362880)

In [ ]:
np.prod(array_data,axis=1) #row wise product

array([  529760,  1441440, 22411950, 13286889])

In [ ]:
np.prod(array_data,axis=0) #rcolumn wise product

array([5215056, 2781240, 3992274, 3927000])

**Statistical functions in Numpy**

## mean()---> Syntax for mean()---> np.mean()---> mean of all values inside the array or matrix

In [ ]:
array_data

array([[56, 43, 11, 20],
       [22, 24, 39, 70],
       [51, 55, 94, 85],
       [83, 49, 99, 33]], dtype=int32)

In [ ]:
np.mean(array_data)

np.float64(52.125)

In [ ]:
np.mean(array_data, axis=1)

array([32.5 , 38.75, 71.25, 66.  ])

In [ ]:
np.mean(array_data, axis=0)

array([53.  , 42.75, 60.75, 52.  ])

## sts()---> it provides with the standard deviation of all values of the matrix or array

In [ ]:
array_data

array([[56, 43, 11, 20],
       [22, 24, 39, 70],
       [51, 55, 94, 85],
       [83, 49, 99, 33]], dtype=int32)

In [ ]:
np.std(array_data)

np.float64(26.67132120836911)

## median() ---> To calculate median of all values in the array or matrix
#syntax for median---> np.median()

In [ ]:
array_data

array([[56, 43, 11, 20],
       [22, 24, 39, 70],
       [51, 55, 94, 85],
       [83, 49, 99, 33]], dtype=int32)

In [ ]:
np.median(array_data)

np.float64(50.0)

# var()---> It helps with calculating the variance of all values inside the array or matrix
#syntax ---> np.var()

In [ ]:
np.var(array_data)

np.float64(711.359375)

### Trigonometric functions

## sin()---> sin value for the value we are going to pass inside it

In [ ]:
np.sin(0)

np.float64(0.0)

In [ ]:
np.sin(60)

np.float64(-0.3048106211022167)

In [ ]:
np.tan(45)

np.float64(1.6197751905438615)

In [ ]:
np.cos(12)

np.float64(0.8438539587324921)

## DOT Product of matrices

## Each dot product operation in a matrix multiplication must follow this rule. Dot products are done between the rows of the first matrix and the columns of the second matrix. Thus, the rows of the first matrix and columns of the second matrix must have the same length.

## syntax for dot product ---> np.dot(matrix1,matrix2)

In [ ]:
matrix1=np.round(np.random.random((3,4))*100).astype('int32')

In [ ]:
matrix2=np.round(np.random.random((4,3))*100).astype('int32')

In [ ]:
matrix1

array([[57, 43, 38, 95],
       [12, 95, 93,  4],
       [21, 92, 66, 18]], dtype=int32)

In [ ]:
matrix2

array([[81,  3, 79],
       [32, 82, 85],
       [86, 21, 82],
       [65, 27, 98]], dtype=int32)

In [ ]:
np.dot(matrix1,matrix2)

array([[15436,  7060, 20584],
       [12270,  9887, 17041],
       [11491,  9479, 16655]], dtype=int32)

## log()--->To calculate the log of all values of our matrix
# syntax for log()---> np.log()

In [ ]:
matrix1

array([[57, 43, 38, 95],
       [12, 95, 93,  4],
       [21, 92, 66, 18]], dtype=int32)

In [ ]:
np.log(matrix1)

array([[4.04305127, 3.76120012, 3.63758616, 4.55387689],
       [2.48490665, 4.55387689, 4.53259949, 1.38629436],
       [3.04452244, 4.52178858, 4.18965474, 2.89037176]])

##exp()---> exponential of all values inside the matrix
## syntax for exp()---> np.exp()

In [ ]:
matrix1

array([[57, 43, 38, 95],
       [12, 95, 93,  4],
       [21, 92, 66, 18]], dtype=int32)

In [ ]:
np.exp(matrix1)

array([[5.68572000e+24, 4.72783947e+18, 3.18559318e+16, 1.81123908e+41],
       [1.62754791e+05, 1.81123908e+41, 2.45124554e+40, 5.45981500e+01],
       [1.31881573e+09, 9.01762841e+39, 4.60718663e+28, 6.56599691e+07]])

## round() ---> it helps with rounding off the float values to its nearest possible integer value
## syntax for round()---> np.round()

In [ ]:
array=np.random.random((3,4))

In [ ]:
array=array*10

In [ ]:
array

array([[0.62647765, 8.33636183, 2.89394707, 9.92330636],
       [7.29212292, 8.51625999, 9.19486695, 6.694965  ],
       [6.32731217, 0.63364197, 1.61634727, 6.70331639]])

In [ ]:
np.round(array)

array([[ 1.,  8.,  3., 10.],
       [ 7.,  9.,  9.,  7.],
       [ 6.,  1.,  2.,  7.]])

round()--->1.6-->2
           1.3-->1
ceil()--->1.6-->2
          1.3-->2
floor()--->1.6-->1
           1.3-->1

## ceil()---> next corresponding value
## syntax for ceil()---> np.ceil()

In [ ]:
np.ceil(array)

array([[ 1.,  9.,  3., 10.],
       [ 8.,  9., 10.,  7.],
       [ 7.,  1.,  2.,  7.]])

## floor()---> It can provide us with the previous value

##syntax for floor()--->np.floor()

In [ ]:
array

array([[0.62647765, 8.33636183, 2.89394707, 9.92330636],
       [7.29212292, 8.51625999, 9.19486695, 6.694965  ],
       [6.32731217, 0.63364197, 1.61634727, 6.70331639]])

In [ ]:
np.floor(array)

array([[0., 8., 2., 9.],
       [7., 8., 9., 6.],
       [6., 0., 1., 6.]])

### Transpose()---> It calculates the transpose of the given matrix

## syntax--> np.transpose() or arr.T

## Transpose--->(i,j)--->(j,i)---> (3,4)---> T ---> (4,3)

In [ ]:
array=np.arange(1,13).reshape(3,4)

In [ ]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
new_array=np.arange(1,17).reshape(4,4)

In [ ]:
new_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
new_array.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [ ]:
np.transpose(new_array)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

## Ravel()---> np.ravel()---> convert nd array into 1d array

In [ ]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
array.ndim

2

In [ ]:
np.ravel(array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Indexing and slicing in Numpy

## Indexing ---> lists[,size-1]---> To have the access over the values

In [ ]:
array=np.round(np.random.random((5,5))*100).astype('int32')

In [ ]:
array

array([[57, 31, 87, 91, 21],
       [44, 19, 98, 33, 57],
       [16, 68, 37, 48, 55],
       [95, 27, 12, 68, 70],
       [ 4, 49, 14, 85, 79]], dtype=int32)

In [ ]:
array1=np.arange(1,10)

In [ ]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array1[6]

np.int64(7)

In [ ]:
array1[8]

np.int64(9)

## Indexing in 2D Array ---> [row,column]
## Indexing in 3D array ---> [z-axis, x-axis, y-axis]

In [ ]:
array

array([[57, 31, 87, 91, 21],
       [44, 19, 98, 33, 57],
       [16, 68, 37, 48, 55],
       [95, 27, 12, 68, 70],
       [ 4, 49, 14, 85, 79]], dtype=int32)

In [ ]:
array[2,3]

np.int32(48)

In [ ]:
array2=np.arange(1,9).reshape(2,2,2)

In [ ]:
array2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
array2[1,0,1]

np.int64(6)

In [ ]:
array2[0,1,0]

np.int64(3)

In [ ]:
array

array([[57, 31, 87, 91, 21],
       [44, 19, 98, 33, 57],
       [16, 68, 37, 48, 55],
       [95, 27, 12, 68, 70],
       [ 4, 49, 14, 85, 79]], dtype=int32)

## Slicing ---> Similar approach just like the list [:]

## 2D Array ---> [row1:row2, col1:col2]

In [ ]:
array[:,2]

array([87, 98, 37, 12, 14], dtype=int32)

In [ ]:
array[0,:]

array([57, 31, 87, 91, 21], dtype=int32)

In [ ]:
array

array([[57, 31, 87, 91, 21],
       [44, 19, 98, 33, 57],
       [16, 68, 37, 48, 55],
       [95, 27, 12, 68, 70],
       [ 4, 49, 14, 85, 79]], dtype=int32)

In [ ]:
array[2:4]

array([[16, 68, 37, 48, 55],
       [95, 27, 12, 68, 70]], dtype=int32)

In [ ]:
array[2:4,3:5]

array([[48, 55],
       [68, 70]], dtype=int32)

In [ ]:
array[2:,1:4]

array([[68, 37, 48],
       [27, 12, 68],
       [49, 14, 85]], dtype=int32)

## Iterating over an array

In [ ]:
array=np.arange(1,10)

In [ ]:
for i in array:
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
array=np.arange(1,17).reshape(4,4)

In [ ]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
for i in array:
  print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [ ]:
for i in array:
  for j in i:
    print(j)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [ ]:
array=np.arange(1,28).reshape(3,3,3)

In [ ]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
for i in array:
  print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


## nditer()---> it can help us out with iterating over every value in a nd array

## np.nditer()

In [ ]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
for i in np.nditer(array):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


## 1D Array ---> value by value on iteration
## 2D Array ---> Row by Row on iteration
## 3D Array ---> 2d Array by 2D Array

## Stacking and Splitting in Array --> size of the arrays must be the same

## Stacking ---> Joining the arrays together
## Horizontal Stacking ---> Row by Row joining is done --> hstack()
## Vertical Stacking ---> Column by Column Joining is done ---> vstack()


In [ ]:
array1=np.arange(1,13).reshape(3,4)

In [ ]:
array1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
array2=np.arange(13,25).reshape(3,4)

In [ ]:
array2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
horizontal_array=np.hstack((array1,array2))

In [ ]:
horizontal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [ ]:
horizontal_array=np.hstack((array1,array2,array1))

In [ ]:
horizontal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 17, 18, 19, 20,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 21, 22, 23, 24,  9, 10, 11, 12]])

In [ ]:
vertical_array=np.vstack((array1,array2))

In [ ]:
vertical_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

## Horizontal split ---> np.hsplit(array, number of parts you want your array to be splitted at)
## Vertical split ---> np.vsplit(array, number of parts you want your array to be splitted at)

In [ ]:
np.hsplit(vertical_array,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [ ]:
np.vsplit(vertical_array,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [ ]:
vertical_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
np.vsplit(vertical_array,3)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]